version: '3.8'

services:
  web-app:
    image: web-tech-image:latest
    container_name: web_container
    build:
      context: . 
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
      - /app/node_modules
    env_file:
      - .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
